# Generated by Django 2.1.7 on 2019-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0002_auto_20190410_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefct',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('artefactname', models.CharField(db_column='ArtefactName', max_length=255, unique=True, verbose_name='Artefacto')),
                ('datecreated', models.DateField(db_column='DateCreated')),
            ],
            options={
                'db_table': 'Artefacto',
                'managed': True,
            },
        ),
    ]
