# Generated by Django 2.1.7 on 2019-04-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0003_artefct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artefct',
            new_name='Artefact',
        ),
    ]
