# Generated by Django 2.1.7 on 2019-04-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_auto_20190412_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pattern',
        ),
        migrations.AddField(
            model_name='pattern',
            name='groups',
            field=models.ManyToManyField(to='Activities.Group'),
        ),
    ]
