# Generated by Django 2.1.7 on 2019-04-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0005_auto_20190413_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='datarealizado',
            field=models.DateField(blank=True, db_column='DataRealizado', null=True),
        ),
    ]
