# Generated by Django 2.1.7 on 2019-05-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0007_auto_20190522_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='artefacto',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='recurso',
        ),
    ]
