# Generated by Django 2.1.7 on 2019-04-10 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Activities', '0002_auto_20190410_1738'),
        ('Processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='pattern',
            field=models.ManyToManyField(to='Activities.Pattern'),
        ),
        migrations.AddField(
            model_name='activity',
            name='processid',
            field=models.ForeignKey(db_column='ProcessID', on_delete=django.db.models.deletion.DO_NOTHING, to='Processes.Process'),
        ),
        migrations.AddField(
            model_name='activity',
            name='role',
            field=models.ManyToManyField(to='Processes.Role'),
        ),
    ]
